language: php
env:
  global:
    - secure: umuKmm0LyPa4enjVtSn4HjUl8kjpuVh9aHUoxJ+mUleELuZO5Nu0F0p4LKkcfSDZeQqdOY+zcfFm2NkRHQu35IxEZjBu9uW88CuA/XaWLTwDJs6RR6JEzLBNQph+42znmUgkaLVdQnn0f8/Jju/rczjOfUY24sr8G/7TafABllyeM1VvxgTLLHPIY+2xUVYoPqTR/SZBz1veW0uPtsevpR6+cP4wIuvWd30GhgK4/nyfepfFkg77nRsx8DR4x5Z3gYGXT2NY7NDEIluUVN912zGUWMd0NPI2vG+B2YJP4nCXkFMaMx0tUjXvuANGnOY+8tj/l3wW+o06UOFCHeY9lECxyGxWH3FzXEGUgBtuf+oy5+sUHuRVO4kul6wXGyiuOGPIJ0ObydOXGJQS0PTJtX+JL76vdsM+DOXejjzJpUszDQeWhhgMEW2355uN06Rt8SoDBJXpF+pNc4Z2sJ0GnC4IjIGpiKzsmF6/01/EuU0N1tVB5+Cg3aqJaDpIkC5XHEuRqivW7KAzU7Kp1NDNflBglsO5zjm43UIZygIalcdZQbG1r2jinrETFtdjShUPjLWtBwaXi1bqisQKTtbBf7X+6QQ8hWuBvHvZGEVAMmePoydy1xMiED2QQUY0UdVqO1hPGVUYnmI6701W8fO0dfK8XOGpCpP8XNzJEVizUQI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    - GIT_BRANCH: master

dist: trusty
sudo: required
matrix:
  fast_finish: true

cache:
  - apt

script:
  - bash .dev-tools/pre-deploy.sh

before_deploy:
  - bash .dev-tools/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "wordpress-attacking-ips.txt"
  skip_cleanup: true
  on:
    repo: mitchellkrogza/Top-Attacking-IP-Addresses-Against-Wordpress-Sites
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  email: false